import Clientlayout from "@/Components/Clientlayout";
import Sidebar from "@/Components/Sidebar";
import { UserProvider } from "@/Context/Usercontext";
import { getuserfromcookies } from "@/helper";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getuserfromcookies();
  const guestcookies = await cookies();
const isguest = guestcookies.get("guest")?.value;


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <UserProvider initialUser={user}>
          <div className="flex">
            <div className=" h-screen">
              <Sidebar />
            </div>

            <main className="-ml-1 md:ml-6 flex-1 ">
              <Clientlayout isGuest={isguest == 'true'}>
              {children}
              </Clientlayout>
            </main>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
